spring:
  application:
    name: product_test
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/db_productos_dev
    username: postgres
    password: admin
  main:
    web-application-type: reactive
server:
  port: 8081
logging:
  level:
    org.springframework.r2dbc: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
