spring:
  application:
    name: pedidos_test
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  main:
    web-application-type: reactive
server:
  port: 8086
ms-productos:
  url: http://localhost:8081
logging:
  level:
    org.springframework.r2dbc: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,refresh
