spring:
  application:
    name: product_test

  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  main:
    web-application-type: reactive

server:
  port: 8085

logging:
  level:
    org.springframework.r2dbc: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,refresh