spring:
  application:
    name: ms-pedidos
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/db_pedidos_dev
    username: postgres
    password: admin
  main:
    web-application-type: reactive
server:
  port: 8082
ms-productos:
  url: http://localhost:8083
logging:
  level:
    org.springframework.r2dbc: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,refresh
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true