spring:
  application:
    name: ms-productos
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/db_productos_dev
    username: postgres
    password: admin
  main:
    web-application-type: reactive
server:
  port: 8081
logging:
  level:
    org.springframework.r2dbc: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      preferIpAddress: true