CREATE TABLE product (
    -- La columna 'id' como clave primaria autoincrementable.
    -- La clase Java usa 'int', pero en PostgreSQL se recomienda SERIAL o INT GENERATED BY DEFAULT AS IDENTITY
    -- para claves primarias enteras autoincrementables.
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- El atributo 'name' se mapea a un VARCHAR para cadenas de texto.
    -- Se asume un tamaño razonable y que no puede ser nulo.
    name VARCHAR(255) NOT NULL,

    -- El atributo 'description' también es una cadena de texto,
    -- usando TEXT para descripciones potencialmente más largas.
    description TEXT,

    -- El atributo 'price' es un float, que se mapea a NUMERIC o REAL/FLOAT en SQL.
    -- NUMERIC(precision, scale) es mejor para datos monetarios para evitar errores de coma flotante.
    price NUMERIC(10, 2) NOT NULL,

    -- El atributo 'stock' es un int, que se mapea a INTEGER en SQL.
    -- Se asume que no puede ser nulo y debe ser mayor o igual a cero.
    stock INTEGER NOT NULL CHECK (stock >= 0)
);